image: node:18.0.0

before_script:
    - apt-get update -qq && apt-get install
    - yarn install

stages:
  - tests

cache:
  paths:
    - ./node_modules

tests:
  stage: tests
  script:
    - echo "Running tests."
    - yarn test
